{{- if .Values.secrets.enabled -}}
# secret for yandex-cloud container registry
---
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.global.yc_secret }}
kind: Secret
metadata:
  name: sirius-registry
type: kubernetes.io/dockerconfigjson

# secret for sirius-gitlab container registry
---
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.global.gitlab_secret }}
kind: Secret
metadata:
  name: gitlab-registry
type: kubernetes.io/dockerconfigjson
{{- end }}