stages:
  - corp
  - univ
  - sirius
#  - cpm

.base-filebeat:
  when: manual
  before_script:
    - echo 'Deploy parameters:'
    - echo 'CLUSTER_NAME =>' ${CLUSTER_NAME}
    - echo 'CI_ENVIRONMENT_SLUG =>' ${CI_ENVIRONMENT_SLUG}
  script:
    - kubectl get ns filebeat-${CI_ENVIRONMENT_SLUG} || kubectl create ns filebeat-${CI_ENVIRONMENT_SLUG}
    - chmod +x ./scripts/helm_deploy_and_wait.sh
    - RELEASE_NAME="filebeat-${CI_ENVIRONMENT_SLUG}"
      NAMESPACE="filebeat-${CI_ENVIRONMENT_SLUG}"
      CHART="chart/${CI_ENVIRONMENT_SLUG}"
      HELM_ARGS="
      -f chart/${CI_ENVIRONMENT_SLUG}/conf/${CLUSTER_NAME}/values.yaml
      -f chart/${CI_ENVIRONMENT_SLUG}/conf/${CLUSTER_NAME}/config.yaml
      --set global.yc_secret="${YC_REGISTRY}"
      --set global.gitlab_secret="${INFRA_REGISTRY}"
      --atomic
      --wait"
      ./scripts/helm_deploy_and_wait.sh

############  CPM  ############

#cpm filebeat stage:
#  extends:
#    - .base-filebeat
#  stage: cpm
#  environment:
#    name: stage
#  variables:
#    CLUSTER_NAME: "cpm-dev"
#  tags:
#    - kube-cpm
#
#cpm filebeat prod:
#  extends:
#    - .base-filebeat
#  stage: cpm
#  environment:
#    name: prod
#  variables:
#    CLUSTER_NAME: "cpm"
#  tags:
#    - cpm-yac

############  CORP  ############

corp filebeat stage:
  extends:
    - .base-filebeat
  stage: corp
  environment:
    name: stage
  variables:
    CLUSTER_NAME: "corp"
  tags:
    - kube-corp

corp filebeat prod:
  extends:
    - .base-filebeat
  stage: corp
  environment:
    name: prod
  variables:
    CLUSTER_NAME: "corp"
  tags:
    - kube-corp

############  UNIV  ############

univ filebeat stage:
  extends:
    - .base-filebeat
  stage: univ
  environment:
    name: stage
  variables:
    CLUSTER_NAME: "univ"
  tags:
    - kube-univ

univ filebeat prod:
  extends:
    - .base-filebeat
  stage: univ
  environment:
    name: prod
  variables:
    CLUSTER_NAME: "univ"
  tags:
    - kube-univ

############  SIRIUS  ############

sirius filebeat stage:
  extends:
    - .base-filebeat
  stage: sirius
  environment:
    name: stage
  variables:
    CLUSTER_NAME: "sirius"
  tags:
    - kube-ci

sirius filebeat prod:
  extends:
    - .base-filebeat
  stage: sirius
  environment:
    name: prod
  variables:
    CLUSTER_NAME: "sirius"
  tags:
    - kube-ci
