stages:
  - cpm-deploy
  - corp-deploy
  - univ-deploy

.base-filebeat:
  when: manual
  before_script:
    - echo 'Deploy parameters:'
    - echo 'CLUSTER_NAME =>' ${CLUSTER_NAME}
    - echo 'CI_ENVIRONMENT_SLUG =>' ${CI_ENVIRONMENT_SLUG}
  script:
    - set -x
    - kubectl get ns filebeat-${CI_ENVIRONMENT_SLUG} || kubectl create ns filebeat-${CI_ENVIRONMENT_SLUG}
    - chmod +x ./scripts/helm_deploy_and_wait.sh
    - RELEASE_NAME="filebeat-${CI_ENVIRONMENT_SLUG}"
      NAMESPACE="filebeat-${CI_ENVIRONMENT_SLUG}"
      CHART="deploy/helm/${CI_ENVIRONMENT_SLUG}"
      HELM_ARGS="
      -f deploy/helm/${CI_ENVIRONMENT_SLUG}/conf/${CLUSTER_NAME}/values.yaml
      --set global.secret="${YC_REGISTRY}"
      --atomic
      --wait"
      ./scripts/helm_deploy_and_wait.sh

cpm-stage filebeat deploy:
  extends:
    - .base-filebeat
  stage: cpm-deploy
  environment:
    name: stage
  variables:
    CLUSTER_NAME: "cpm-dev"
  tags:
    - kube-cpm

cpm-prod filebeat deploy:
  extends:
    - .base-filebeat
  stage: cpm-deploy
  environment:
    name: prod
  variables:
    CLUSTER_NAME: "cpm"
  tags:
    - cpm-yac

corp-stage filebeat deploy:
  extends:
    - .base-filebeat
  stage: corp-deploy
  environment:
    name: stage
  variables:
    CLUSTER_NAME: "corp"
  tags:
    - kube-corp

corp-prod filebeat deploy:
  extends:
    - .base-filebeat
  stage: corp-deploy
  environment:
    name: prod
  variables:
    CLUSTER_NAME: "corp"
  tags:
    - kube-corp

univ-stage filebeat deploy:
  extends:
    - .base-filebeat
  stage: univ-deploy
  environment:
    name: stage
  variables:
    CLUSTER_NAME: "univ"
  tags:
    - kube-univ

univ-prod filebeat deploy:
  extends:
    - .base-filebeat
  stage: univ-deploy
  environment:
    name: prod
  variables:
    CLUSTER_NAME: "univ"
  tags:
    - kube-univ

#sirius-stage filebeat deploy:
#  extends:
#    - .base-filebeat
#  stage: sirius-deploy
#  environment:
#    name: stage
#  variables:
#    CLUSTER_NAME: "sirius"
#  tags:
#    - kube-ci

#sirius-prod filebeat deploy:
#  extends:
#    - .base-filebeat
#  stage: sirius-deploy
#  environment:
#    name: prod
#  variables:
#    CLUSTER_NAME: "sirius"
#  tags:
#    - kube-ci
