# Add config file filebeat.yml for daemonset in /usr/share/filebeat
daemonset:
  filebeatConfig:
    filebeat.yml: |-
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            templates:
              - condition:
                  regexp:
                    kubernetes.container.name: "elastic|herald|calendar|telegram|tracker|passport|staff|process-tms|web|gen-changes-report-cronjob|odyssey|postgres|cheops-auth|cheops-email|cyrus|cron|lab-noo|lab-front|lab-smt|noo-back|noo-front|noo-storage|smt-cache|smt-front|smt-noo-front|smt-persist|smt-portal"
                config:
                  - type: container
                    containers.ids:
                    - '*'
                    paths:
                      - /var/log/containers/*${data.kubernetes.container.id}.log
                    scan_frequency: 15s
                    ignore_older: 36h
                    close_inactive: 5m
                    close_removed: true
                    clean_removed: true
                    processors:
                      - decode_json_fields:
                          fields: ['message']
                          target: json
                      - dissect:
                          when:
                            contains:
                              kubernetes.container.name: odyssey
                          tokenizer: "[%{timestamp}] %{level} %{context} %{database} %{connection} %{message}"
                          field: "message"
                          target_prefix: "json"
                      - drop_event:
                          when:
                            equals:
                              json.context: console
                      - drop_event:
                          when:
                            equals:
                              json.context: auth
                      - drop_event:
                          when:
                            equals:
                              json.level: info
      output.elasticsearch:
        host: '${NODE_NAME}'
        hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master.logging.svc:9200}'
        filebeat.registry.flush: 2s
      logging.metrics.enabled: false
