---
daemonset:
  resources:
    limits:
      cpu: 300m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 50Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role
          operator: In
          values:
          - postgres
          - stage

imagePullSecrets:
- name: infra-registry

tolerations:
- effect: NoSchedule
  key: node-role
  operator: Equal
  value: stage
- effect: NoSchedule
  key: app
  operator: Equal
  value: postgres

secrets:
  enabled: false