apiVersion: v1
description: Official Elastic helm chart for Filebeat
home: https://github.com/elastic/helm-charts
maintainers:
  - email: helm-charts@elastic.co
    name: Elastic
name: filebeat-{{ .Values.global.env }}
version: {{ .Values.imageTag }}
appVersion: {{ .Values.imageTag }}
sources:
  - https://github.com/elastic/beats
icon: https://helm.elastic.co/icons/beats.png
