daemonset:
  filebeatConfig:
    filebeat.yml: |-
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            templates:
              - condition:
                  regexp:
                    kubernetes.container.name: "herald|cron|cyrus|cheops-auth|cheops-email|lab-front|lab-noo|lab-smt|noo-back|noo-front|noo-storage|smt-cache|smt-front|smt-noo-front|smt-persist|smt-portal"
                config:
                  - type: container
                    containers.ids:
                    - '*'
                    paths:
                      - /var/log/containers/*${data.kubernetes.container.id}.log
                    scan_frequency: 15s
                    ignore_older: 36h
                    close_inactive: 5m
                    close_removed: true
                    clean_removed: true
                    processors:
                      - decode_json_fields:
                          fields: ['message']
                          target: json
      output.elasticsearch:
        host: '${NODE_NAME}'
        hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master.logging.svc:9200}'
        filebeat.registry.flush: 2s
      logging.metrics.enabled: false
