---
daemonset:
  resources:
    limits:
      cpu: 300m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 50Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - app-stage-1
          - db-stage

imagePullSecrets:
- name: sirius-registry
- name: gitlab-registry

tolerations:
- effect: NoSchedule
  key: node-role
  operator: Equal
  value: db-stage
- effect: NoSchedule
  key: node-role
  operator: Equal
  value: stage