---
daemonset:
  resources:
    limits:
      cpu: 300m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 50Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role
          operator: In
          values:
          - ejudge
          - postgres-failover
          - stage

imagePullSecrets:
- name: sirius-registry
- name: gitlab-registry

tolerations:
- effect: NoSchedule
  key: node-role
  operator: Equal
  value: stage
- effect: NoSchedule
  key: node-role
  operator: Equal
  value: postgres-failover
